name: Daily Commit

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update file
        run: |
          echo "Last Update: $(date)" > daily.txt

      - name: Commit changes
        run: |
          git config user.name "txger."
          git config user.email "simaocampanico.dev@gmail.com"
          git add daily.txt
          git commit -m "New commit at private repository" || echo "Nothing to commit"
          git push
